# Generated by Django 4.0.2 on 2022-02-25 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.author')),
                ('follow_requests', models.ManyToManyField(related_name='follow_requests', to='api.FollowRequest')),
                ('posts', models.ManyToManyField(related_name='posts', to='api.Post')),
            ],
        ),
    ]
