# Generated by Django 4.0.2 on 2022-02-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
