# Generated by Django 4.0.2 on 2022-03-01 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_id_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_sent', to='api.author'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_received', to='api.author'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.author'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='follow_requests',
            field=models.ManyToManyField(to='api.FollowRequest'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(to='api.Post'),
        ),
    ]
