# Generated by Django 4.0.2 on 2022-03-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inbox_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ManyToManyField(to='api.Comment'),
        ),
    ]
