# Generated by Django 4.0.2 on 2022-02-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('visibility', models.CharField(max_length=10)),
                ('published', models.DateField()),
                ('source', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
