# Generated by Django 4.0.2 on 2022-02-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_followrequest'),
        ('api', '0003_post'),
    ]

    operations = [
    ]
