# Generated by Django 4.0.2 on 2022-03-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inbox_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewableBy',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
