# Generated by Django 4.0.2 on 2022-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='content', max_length=10000),
            preserve_default=False,
        ),
    ]
