# Generated by Django 4.0.2 on 2022-03-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_viewableby'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('actor', 'object')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'object')},
        ),
    ]
