# Generated by Django 4.0.2 on 2022-03-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_followrequest_actor_alter_followrequest_object_and_more'),
        ('api', '0005_alter_like_author'),
    ]

    operations = [
    ]
