# Generated by Django 4.0.2 on 2022-03-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comment_id'),
        ('api', '0006_merge_20220301_1939'),
    ]

    operations = [
    ]
