# Generated by Django 4.0.2 on 2022-02-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_0002_followrequest_0003_post'),
        ('api', '0006_alter_post_content'),
    ]

    operations = [
    ]
