# Generated by Django 4.0.2 on 2022-03-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_0003_alter_comment_id_0006_merge_20220301_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(to='api.Like'),
        ),
    ]
