# Generated by Django 4.0.2 on 2022-02-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20220221_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.author')),
                ('follow_requests', models.ManyToManyField(to='api.FollowRequest')),
                ('posts', models.ManyToManyField(to='api.Post')),
            ],
        ),
    ]
