# Generated by Django 4.0.2 on 2022-03-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
