# Generated by Django 4.0.2 on 2022-02-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='follow_requests',
            field=models.ManyToManyField(related_name='follow_requests', to='api.FollowRequest'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='api.Post'),
        ),
    ]
