# Generated by Django 4.0.2 on 2022-03-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_author_profileimage.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='baseUrl',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
