version: '3.1'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
  server:
    build:
      context: ../distributed_social_network
      dockerfile: Dockerfile
    restart: always
