version: '3.1'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://backend-404.herokuapp.com
    ports:
      - 80:80
  server:
    build:
      context: ../distributed_social_network
      dockerfile: Dockerfile
    restart: always
