version: '3.1'
services:
  db:
      image: postgres:14
      restart: always
      environment:
        - POSTGRES_DB=social_network
        - POSTGRES_USER=username
        - POSTGRES_PASSWORD=password
      ports:
        - '5438:5432'
      volumes: 
        - postgres-data:/var/lib/postgresql/data
  server:
    build:
      context: ../distributed_social_network
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      DB_NAME: social_network
      DB_USER: username
      DB_HOST: db
      DB_PASSWORD: password
      DB_PORT: 5432
      HOST_SERVER: localhost
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_IPV4ADDRESS= 127.0.0.1
    ports:
      - 80:80
volumes:
  postgres-data:
  