name: Heroku Deploy CICD

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ secrets.GROUP_EMAIL }}
          api_key: ${{ secrets.GROUP_API_KEY }}
          docker_compose_file: "./deploy/docker-compose.heroku.yml"
          heroku_apps: '[{"imagename":"deploy_frontend","appname":"frontend404","apptype":"web"}, {"imagename":"deploy_server","appname":"backend-404","apptype":"web"}]'
